### PR TITLE
Add logparser step that returns a LogParserResult for use in pipeline scripts

### PR DESCRIPTION
**Pull request by slide**
This adds an explicit logparser step for pipeline that returns a LogParserResult for use in pipeline scripts. Pipelines could then check some of the values of the LogParserResult for decision making.

### CODE REVIEW

**Comment by slide** [comment]
Looks like the build server has JDK 1.7, which doesn't know about -Xdoclint:none.

**Comment by herau** [comment]
@slide Does it solve [JENKINS 32866](https://issues.jenkins-ci.org/browse/JENKINS-32866)

**Comment by slide** [comment]
@herau No, it only gives access to the results of the log parser for use in the pipeline script so that decisions can be made based on the parser results.

**Comment by hypery2k** [comment]
if you're still interested in this feature, please open a new PR against develop

**Pull request closed without merging**
