### PR TITLE
Patched in a PASS condition

### PR DESCRIPTION
**Pull request by CptSpaceToaster**
## Patched in a PASS condition

I was looking to count warnings, errors, and passes with this pluggin.  Upon finding out that INFO was a general catch-all, I decided to patch in a specific case to count "Passes"
**Parser Configuration:**

```
error /^error/
warn /^warn/
pass /^pass/
```

**Job:**

```
echo hi
echo pass
echo warn
echo 1
echo error
echo 2
```

parsed-console-output

### CODE REVIEW

**Comment by CptSpaceToaster** [comment]
TODO: Passes show up as warnings on the build summary: 
issue

**Comment by jborghi** [comment]
I am not clear on the objective of the 'pass' identifier, nor sure it fits with this plugin. The plugin parses logs to determine if the build should fail (on error condition) or be marked unstable (on warning condition). Any other line is considered a pass by default. Introducing both a specific 'pass' and a 'fail' condition in the same build seems to cause an undetermined state.

If the objective is to count the number of lines that were neither error nor warn, as a sort of 'total lines parsed' counter, then it shouldn't use a distinct configuration. I'm not sure everyone would like that info however, as it may be considered clutter. If the objective is to identify some 'interesting' lines, but use some other wording than 'info', perhaps that text should be configurable (in the display, not configuration)?

**Comment by CptSpaceToaster** [comment]
We were using this pluggin to monitor the status on a mile logs that encompassed building, installing, booting, and testing.  Simply put, we wanted to count our test passes using this pluggin, as we wouldn't limit ourselves to one testing framework.  

If our "test" was to boot an emulated PC, then seeing `device: Ready` may be a success condition.  If we ran a more formal resting suite, we could count the number of tests that passed, and tests that failed.

here's a close approximation of our config now:
```
ok /Failed to build linux/

error /^TEST-FAIL:/
error /(?i)^error/

warning /^TEST-WARN:/
warning /^TEST-WARNING:/
warning /(?i)warning/

pass /^TEST-PASS:/

start /^TEST-START:/
```

We're simply parsing messages out of our log... and seeing that INFO became quite cluttered, we required another method to mark that a success occurred.  Having 200 fails, 100 warns, and 800 Infos doesn't really indicate how "good" you did.  With Success, and Starts, and Info packed together under one bubble, we couldn't quite use it out of the box.

**Comment by jborghi** [comment]
Why not just use the 'info' configuration to indicate the pass count? If the answer is you'd like more than one type of 'info' line that shows up in the build statistics, but has no bearing on the build result (as warning and error do), I think making this a configurable entity would be best - allow configuring a list of 'information only' entities, and the associated patterns to look for. Or perhaps I am missing how 'pass' is fundamentally different from 'info'?

**Comment by CptSpaceToaster** [comment]
**This comment is WIP, expect some edits until you see this message disappear**

That's what we initially tried to do.  However, during initial planning, we didn't like that anything not considered a warning or an error was just lumped into "INFO"  Nothing really changed, we just lost our ability to gather output from our tests.  

We COULD report test-case passes in "INFO" but that doesn't tell us how our tests performed.  We wanted to count the number of "Green Lights" and "Red Lights" that could occur during our complicated build process...

Example:
Build errors: 0 <- Note, if you had a build error, the tests would most likely not run :)
Build warnings: 166
Tests Pass: 3
Tests Fail: 1
Tests Run: 4

Under the old behavior, we could mark errors and warnings as expected, but then we'd have to use INFO and START to count the pass conditions, and start conditions:
```
Error: 1
Warn: 166
Info: 7
```
So... my manager might come and ask... 
"How many things failed?, Answer 1
"How many things passed?, Uhhhhhh
"How many things were run?", Uhhhhhh

Now... I could go look at the test runner, and count.  I could make a line report this information at the end... but... for simplicity's sake, I just wanted the log parser to provide that information.  

So now, I get:
```
Error: 1
Warn: 166
Pass: 3
Info: 4
```
Nice Bonuses include
- Links to the occurrence in the mile long log :)
- I can count "yellow lights" and warnings that may have occurred
- Proper answer to the questions:
"How many things failed?", Answer 1
"How many things passed?, Answer 3
"How many things were run?", Answer 4

Additionally, if I wanted to mark other important messages, as our build environment transitions to a new phase, I wouldn't fear adding them to INFO, as I can simply sum fails + passes to arrive at the total number of tests.

In a very roundabout sense, we simply wanted the log parser to provide the number of red lights, and green lights (and maybe yellow lights) on our monster of a build.  If you want to extend the behavior of INFO to somehow reflect this, I'd be fine with it.  

The requirement is that I needed to be able to answer these questions by looking at the summary:
"How many things failed?" and "How many things passed?"

**Comment by CptSpaceToaster** [comment]
Was there any other discussion that you wanted to have?

**Comment by CptSpaceToaster** [comment]
self-promoting bump...

**Comment by jborghi** [comment]
Hi,

The objective of this plugin is to set the overall build result by parsing the build log.

The words 'pass' and 'fail' are typically mutually exclusive with respect to 'build result', so having a build with 'pass' conditions that also has 'fail' conditions is indeterminate. I think 'pass' to you means 'info', but that seems confusing in the general case, and likely will be to others. As such, I would not recommend implementing this as a general feature. To support your use case, I would suggest introducing a configurable list of 'info' type items, and let the user call them whatever seems pleasing, even if confusing to some :)

However:
1. I understand your use case, and although the plugin was not designed to support it (the megabuild log with multiple pass/fail sections), the usage seems logical for your specific situation.
2. The plugin has not been released/maintained for many years, so if you would like to make your changes public and take ownership, that would probably be great for the community as the plugin could benefit from some ongoing active management.

**Comment by aspiers** [comment]
Based on a skim read, I think #14 might cater for this?

**Comment by CptSpaceToaster** [comment]
#14 looks solves this problem very well.  I'd like to see some ability to customize the colors being used, but other than a small bit of fanciness, that PR looks much better than what I was going for.

**Comment by aspiers** [comment]
Except unfortunately #14 has now been closed without merging.  Hopefully someone can resurrect it.

**Comment by hypery2k** [comment]
will take look at this next week: https://github.com/jenkinsci/log-parser-plugin/pull/25

**Pull request closed without merging**
