### PR TITLE
Remove agent-to-controller calls

### PR DESCRIPTION
**Pull request by jglick**
Compatible with https://github.com/jenkinsci/jenkins/pull/5885. See https://github.com/jenkinsci/remoting-security-workaround-plugin/blob/main/README.adoc#affected-functionality.

### CODE REVIEW

**Comment by n-marion** [comment]
@jglick , is it safe to say this would resolve the following error we are getting now that our server has been updated to Jenkins 2.303.3?

```
Error when executing always post condition:
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to channel
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1797)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
		at hudson.remoting.Channel.call(Channel.java:1001)
		at hudson.FilePath.act(FilePath.java:1166)
		at hudson.FilePath.act(FilePath.java:1155)
		at hudson.FilePath.copyTo(FilePath.java:2493)
		at hudson.FilePath.copyTo(FilePath.java:2448)
		at hudson.plugins.logparser.LogParserStatusComputer.computeStatusMatches(LogParserStatusComputer.java:88)
		at hudson.plugins.logparser.LogParserStatusComputer.access$000(LogParserStatusComputer.java:22)
		at hudson.plugins.logparser.LogParserStatusComputer$1.call(LogParserStatusComputer.java:54)
		at hudson.plugins.logparser.LogParserStatusComputer$1.call(LogParserStatusComputer.java:47)
		at hudson.remoting.UserRequest.perform(UserRequest.java:211)
		at hudson.remoting.UserRequest.perform(UserRequest.java:54)
		at hudson.remoting.Request$2.run(Request.java:376)
		at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
java.lang.SecurityException: Agent tried to access build directory of a build not currently running on this system. Learn more: https://www.jenkins.io/redirect/security-144/
	at jenkins.security.s2m.RunningBuildFilePathFilter.op(RunningBuildFilePathFilter.java:128)
	at jenkins.ReflectiveFilePathFilter.read(ReflectiveFilePathFilter.java:21)
	at jenkins.FilePathFilterAggregator.read(FilePathFilterAggregator.java:75)
	at jenkins.SoloFilePathFilter.read(SoloFilePathFilter.java:66)
	at hudson.FilePath.reading(FilePath.java:3497)
	```

**Comment by jglick** [comment]
@n-marion yes it should. You can build yourself a snapshot to confirm.

**Comment by n-marion** [comment]
@jglick ,

I was not successful on building it myself due to an unknown build status, but I was able to obtain your PR's .hpi file from Jenkins. Will need to wait until I can restart our Jenkins server before applying this, but when I do, I will let you know.

Thanks.

**Comment by daniel-beck** [comment]
Interesting, I didn't think that would happen. What job type is that, and if it's a Pipeline, what version of https://plugins.jenkins.io/workflow-durable-task-step/ is installed?

**Comment by n-marion** [comment]
Using the PR’s .hpi resolved my issue I saw. Log Parser is now working properly. 

@daniel-beck , not sure if that question was to me? If so, I can check tomorrow as I’m out of office today.

**Comment by jglick** [comment]
I just tried the released version of this plugin on a freestyle project in a Jenkins dev build. It worked. (With https://github.com/jenkinsci/jenkins/pull/5890, a warning is printed to the system log as expected.) Also worked from a Pipeline project using `mock-slave`

```groovy
node('mock') {
    sh 'echo "ERROR oops"'
    logParser parsingRulesPath: '/path/to/log-parser.txt', useProjectRule: false
}
```

with that file being

```
# https://plugins.jenkins.io/log-parser/
error /ERROR/
```

I suspect @n-marion had just neglected to update `workflow-durable-task-step` as mentioned in the security advisory.

**Comment by daniel-beck** [comment]
> @daniel-beck , not sure if that question was to me? If so, I can check tomorrow as I’m out of office today.

Yes, sorry for being ambiguous. Thanks in advance. While Jesse's comment is a good indicator, having confirmation is best.

Specifically, this is about https://www.jenkins.io/doc/upgrade-guide/2.303/#SECURITY-2428 (third paragraph, which in hindsight is probably neither discoverable nor clear enough — and we shouldn't have reused the generic `/security-144` redirect URL either).

**Comment by n-marion** [comment]
Hi @daniel-beck ,

Yes the version of the Pipeline: Nodes and Agents, 2.39; so it isn't the latest. The problem is that the Jenkins server we're running on has a bit of disconnect between those that own the actual Jenkins instance and update that version, those that manage the usage of the system and configuration, and our end users who use it. 

The team that updated the system to 2.303.3 doesn't manage our plugins. As both a user and an admin, my job was broken and that began my investigation from the `log-parser` perspective. As I am only 1 of about 30+ teams to use this system, updating plugins really focuses on compatible first and incompatible as a need be. (As it impacts 100s of jobs that we do not manage ourselves)

Anyways, this is a good learning experience for our admin team to understand the LTS Release changes prior to the owners updating the system. _Hopefully they'll give us a bit more warning next time._

For now, I will stick with the working log parser plugin from this PR, as for an end-user; it doesn't require changes on their end. And we'll look into the incompatible changes and see which of the hundreds of jobs may be affected, if at all.

Thanks for the help!

**Comment by jglick** [comment]
@hypery2k are you still maintaining this plugin? This is a critical fix.

**Comment by daniel-beck** [comment]
@n-marion 

> The team that updated the system to 2.303.3 doesn't manage our plugins.

I recommend they read the upgrade guide before doing so in the future, as I point out above, this plugin update requirement is documented.

**Comment by jglick** [comment]
RPU lists @recena & @hypery2k as maintainers, with no response from the latter. Given that this plugin is the most popular by far of those known to be broken by the proposed security hardening, I think we need to start the two-week timer and request emergency authorization to merge & release this PR. WDYT @daniel-beck?

Beware the nonstandard https://github.com/jenkinsci/log-parser-plugin/blob/master/RELEASE.md

**Pull request merged**
